hub:
  image: selenium/hub
  restart: always
  environment: 
    - GRID_TIMEOUT=240000
    - GRID_BROWSER_TIMEOUT=290
  ports:
    - "4444:4444"
firefox:
  image: selenium/node-firefox
  restart: always
  links:
    - hub
