hub:
  image: selenium/hub:2.47.1
  restart: always
  environment: 
    - GRID_TIMEOUT=160000
    - GRID_BROWSER_TIMEOUT=240000
    - GRID_MAX_SESSION=1
    - GRID_NODE_POLLING=5000
    - GRID_CLEAN_UP_CYCLE=5000
    - GRID_UNREGISTER_IF_STILL_DOWN_AFTER=90000
  ports:
    - "4444:4444"
firefox:
  image: selenium/node-firefox:2.47.1
  restart: always
  links:
    - hub
